<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>grupo06_ur10e_bringup</name>
  <version>1.0.0</version>
  <description>Launch de visualización del UR10e (RViz2, robot_state_publisher y GUI opcional) para IMT-342, Grupo 6.</description>
  <maintainer email="marcojaldinmendoza@gmail.com">Marco Jaldin</maintainer>
  <author>Sebastian Arinez</author>
  <author email="marcojaldinmendoza@gmail.com">Marco Jaldin</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>rmw_cyclonedds_cpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
